version: '3'
services:
  myapp-main:
    image: golf-club-api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_club_db
      #- spring.datasource.url=jdbc:mysql://s4-fall-2022.ce2vcezehro2.us-east-1.rds.amazonaws.com/fall_2022
      - spring.datasource.password=Keyin2024
      - spring.datasource.username=root